name: CI

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.7'
      - name: Install Power BI tools
        run: npm install -g powerbi-visuals-tools
        shell: powershell
      - name: Install npm packages
        run: npm install
        shell: powershell
      - name: Package custom viz
        run: pbiviz package
        shell: powershell
